version: 2

models:
  - name: dim_marketplace
    description: ""
    columns:
      - name: marketplace_sk
        data_type: string
        description: ""

      - name: marketplace_id
        data_type: string
        description: ""

      - name: marketplace_name
        data_type: string
        description: ""

      - name: region
        data_type: string
        description: ""

      - name: marketplace_endpoint_url
        data_type: string
        description: ""

  - name: dim_portfolio_code
    description: ""
    columns:
      - name: portfolio_code_sk
        data_type: string
        description: ""

      - name: portfolio_code
        data_type: string
        description: ""

      - name: parent_code
        data_type: string
        description: ""

      - name: product_type
        data_type: string
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

  - name: dim_product
    description: ""
    columns:
      - name: product_sk
        data_type: string
        description: ""

      - name: sku
        data_type: string
        description: ""

      - name: asin
        data_type: string
        description: ""

      - name: product_type
        data_type: string
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: parent_code
        data_type: string
        description: ""

      - name: shaker_code
        data_type: string
        description: ""

      - name: portfolio_code
        data_type: string
        description: ""

      - name: product_code
        data_type: string
        description: ""

      - name: product_color_code
        data_type: string
        description: ""

      - name: product_color
        data_type: string
        description: ""

      - name: product_pack_size
        data_type: string
        description: ""

  - name: dim_tenant
    description: ""
    columns:
      - name: tenant_sk
        data_type: string
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: company_name
        data_type: string
        description: ""