version: 2

models:
  - name: stg_rankings__h10_keyword_tracker
    description: ""
    columns:
      - name: date_added
        data_type: timestamp
        description: ""

      - name: created_at
        data_type: datetime
        description: ""

      - name: updated_at
        data_type: datetime
        description: ""

      - name: asin
        data_type: string
        description: ""

      - name: title
        data_type: string
        description: ""

      - name: keyword
        data_type: string
        description: ""

      - name: marketplace_url
        data_type: string
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: organic_rank
        data_type: int64
        description: ""

      - name: search_volume
        data_type: numeric
        description: ""

      - name: sponsored_position
        data_type: numeric
        description: ""