version: 2

models:
  - name: int_add_fields_to_joined_orders
    description: ""
    columns:
      - name: amazon_order_id
        data_type: string
        description: ""

      - name: order_item_id
        data_type: int64
        description: ""

      - name: purchase_datetime
        data_type: timestamp
        description: ""

      - name: purchase_date
        data_type: date
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: sales_channel
        data_type: string
        description: ""

      - name: asin
        data_type: string
        description: ""

      - name: seller_sku
        data_type: string
        description: ""

      - name: order_status
        data_type: string
        description: ""

      - name: quantity_ordered
        data_type: int64
        description: ""

      - name: promotion_ids
        data_type: string
        description: ""

      - name: product_info_number_of_items
        data_type: int64
        description: ""

      - name: item_price_currency_code
        data_type: string
        description: ""

      - name: item_price_amount
        data_type: numeric
        description: ""

      - name: item_tax_amount
        data_type: numeric
        description: ""

      - name: promotion_discount_tax_currency_code
        data_type: string
        description: ""

      - name: output_vat
        data_type: numeric
        description: ""

      - name: item_tax_currency_code
        data_type: string
        description: ""

      - name: promotion_discount_tax_amount
        data_type: numeric
        description: ""

      - name: promotion_discount_currency_code
        data_type: string
        description: ""

      - name: promotion_discount_amount
        data_type: numeric
        description: ""

      - name: coupon_fee
        data_type: numeric
        description: ""

      - name: tax_collection_model
        data_type: string
        description: ""

      - name: tax_collection_responsible_party
        data_type: string
        description: ""

      - name: is_prime
        data_type: boolean
        description: ""

      - name: is_replacement_order
        data_type: boolean
        description: ""

      - name: replaced_order_id
        data_type: string
        description: ""

      - name: is_gift
        data_type: string
        description: ""

      - name: is_vine
        data_type: boolean
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: shipping_price_amount
        data_type: numeric
        description: ""

      - name: shipping_price_currency_code
        data_type: string
        description: ""

      - name: shipping_discount_amount
        data_type: numeric
        description: ""

      - name: shipping_discount_currency_code
        data_type: string
        description: ""

      - name: buyer_info_gift_wrap_price_amount
        data_type: numeric
        description: ""

      - name: buyer_info_gift_wrap_price_currency_code
        data_type: string
        description: ""

  - name: int_aggregate_joined_orders_with_added_fields
    description: ""
    columns:
      - name: purchase_date
        data_type: date
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: order_status
        data_type: string
        description: ""

      - name: asin
        data_type: string
        description: ""

      - name: seller_sku
        data_type: string
        description: ""

      - name: item_price_currency_code
        data_type: string
        description: ""

      - name: is_vine
        data_type: boolean
        description: ""

      - name: is_replacement_order
        data_type: boolean
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: product_code
        data_type: string
        description: ""

      - name: quantity_ordered
        data_type: int64
        description: ""

      - name: item_price_amount
        data_type: numeric
        description: ""

      - name: promotion_discount_amount
        data_type: numeric
        description: ""

      - name: item_tax_amount
        data_type: numeric
        description: ""

      - name: shipping_price_amount
        data_type: numeric
        description: ""

      - name: shipping_discount_amount
        data_type: numeric
        description: ""

      - name: buyer_info_gift_wrap_price_amount
        data_type: numeric
        description: ""

      - name: output_vat
        data_type: numeric
        description: ""

      - name: coupon_fee
        data_type: numeric
        description: ""

  - name: int_calculate_fields_for_aggregated_joined_orders
    description: ""
    columns:
      - name: purchase_date
        data_type: date
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: order_status
        data_type: string
        description: ""

      - name: asin
        data_type: string
        description: ""

      - name: seller_sku
        data_type: string
        description: ""

      - name: item_price_currency_code
        data_type: string
        description: ""

      - name: is_vine
        data_type: boolean
        description: ""

      - name: is_replacement_order
        data_type: boolean
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: product_code
        data_type: string
        description: ""

      - name: quantity_ordered
        data_type: int64
        description: ""

      - name: item_price_amount
        data_type: numeric
        description: ""

      - name: promotion_discount_amount
        data_type: numeric
        description: ""

      - name: item_tax_amount
        data_type: numeric
        description: ""

      - name: output_vat
        data_type: numeric
        description: ""

      - name: coupon_fee
        data_type: numeric
        description: ""

      - name: net_item_price_per_unit
        data_type: numeric
        description: ""

      - name: net_item_price_amount
        data_type: numeric
        description: ""

      - name: referral_fee_pct
        data_type: numeric
        description: ""

      - name: referral_fees
        data_type: numeric
        description: ""