version: 2

models:
  - name: dim_ad_types
    description: ""
    columns:
      - name: ad_type_sk
        data_type: string
        description: ""

      - name: ad_type
        data_type: string
        description: ""

  - name: dim_campaigns
    description: ""
    columns:
      - name: campaign_sk
        data_type: string
        description: ""

      - name: campaign_id
        data_type: int64
        description: ""

      - name: campaign_name
        data_type: string
        description: ""

      - name: campaign_status
        data_type: string
        description: ""

      - name: start_date
        data_type: date
        description: ""

      - name: end_date
        data_type: date
        description: ""

      - name: is_current
        data_type: boolean
        description: ""

  - name: dim_placements
    description: ""
    columns:
      - name: placement_sk
        data_type: string
        description: ""

      - name: placement_classification
        data_type: string
        description: ""

  - name: dim_portfolios
    description: ""
    columns:
      - name: portfolio_sk
        data_type: string
        description: ""

      - name: portfolio_id
        data_type: int64
        description: ""

      - name: portfolio_name
        data_type: string
        description: ""

      - name: tenant_sk
        data_type: string
        description: ""

  - name: dim_ppc_products
    description: ""
    columns:
      - name: ppc_product_sk
        data_type: string
        description: ""

      - name: parent_code
        data_type: string
        description: ""

      - name: portfolio_code
        data_type: string
        description: ""

      - name: product_code
        data_type: string
        description: ""

      - name: product_color
        data_type: string
        description: ""

      - name: product_pack_size
        data_type: string
        description: ""

  - name: fct_campaign_placements
    description: ""
    columns:
      - name: record_date
        data_type: date
        description: ""

      - name: campaign_sk
        data_type: string
        description: ""

      - name: portfolio_sk
        data_type: string
        description: ""

      - name: marketplace_sk
        data_type: string
        description: ""

      - name: placement_sk
        data_type: string
        description: ""

      - name: tenant_sk
        data_type: string
        description: ""

      - name: ad_type_sk
        data_type: string
        description: ""

      - name: ppc_product_sk
        data_type: string
        description: ""

      - name: impressions
        data_type: int64
        description: ""

      - name: clicks
        data_type: int64
        description: ""

      - name: units_sold_clicks
        data_type: int64
        description: ""

      - name: sales_clicks_usd
        data_type: numeric
        description: ""

      - name: purchases_clicks
        data_type: int64
        description: ""

      - name: campaign_budget_amount_usd
        data_type: numeric
        description: ""

      - name: cost_usd
        data_type: numeric
        description: ""

      - name: cost_per_click_usd
        data_type: numeric
        description: ""

      - name: click_through_rate
        data_type: float64
        description: ""

      - name: conversion_rate
        data_type: float64
        description: ""

  - name: fct_campaigns
    description: ""
    columns:
      - name: record_date
        data_type: date
        description: ""

      - name: ad_type_sk
        data_type: string
        description: ""

      - name: campaign_sk
        data_type: string
        description: ""

      - name: marketplace_sk
        data_type: string
        description: ""

      - name: portfolio_sk
        data_type: string
        description: ""

      - name: ppc_product_sk
        data_type: string
        description: ""

      - name: tenant_sk
        data_type: string
        description: ""

      - name: impressions
        data_type: int64
        description: ""

      - name: clicks
        data_type: int64
        description: ""

      - name: units_sold_clicks
        data_type: int64
        description: ""

      - name: sales_clicks_usd
        data_type: numeric
        description: ""

      - name: campaign_budget_amount_usd
        data_type: numeric
        description: ""

      - name: cost_usd
        data_type: numeric
        description: ""

      - name: cost_per_click_usd
        data_type: numeric
        description: ""

      - name: click_through_rate
        data_type: float64
        description: ""

      - name: conversion_rate
        data_type: float64
        description: ""

      - name: top_of_search_impression_share
        data_type: numeric
        description: ""

  - name: obt_campaigns
    description: ""
    columns:
      - name: date
        data_type: date
        description: ""

      - name: created_at
        data_type: datetime
        description: ""

      - name: updated_at
        data_type: datetime
        description: ""

      - name: campaign_id
        data_type: int64
        description: ""

      - name: campaign_name
        data_type: string
        description: ""

      - name: campaign_status
        data_type: string
        description: ""

      - name: portfolio_id
        data_type: numeric
        description: ""

      - name: portfolio_name
        data_type: string
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: impressions
        data_type: int64
        description: ""

      - name: clicks
        data_type: int64
        description: ""

      - name: units_sold_clicks
        data_type: int64
        description: ""

      - name: sales_clicks_usd
        data_type: numeric
        description: ""

      - name: campaign_budget_amount_usd
        data_type: numeric
        description: ""

      - name: cost_usd
        data_type: numeric
        description: ""

      - name: cost_per_click_usd
        data_type: numeric
        description: ""

      - name: click_through_rate
        data_type: float64
        description: ""

      - name: conversion_rate
        data_type: float64
        description: ""

      - name: top_of_search_impression_share
        data_type: numeric
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: ad_type
        data_type: string
        description: ""

      - name: parent_code
        data_type: string
        description: ""

      - name: portfolio_code
        data_type: string
        description: ""

      - name: product_code
        data_type: string
        description: ""

      - name: product_color
        data_type: string
        description: ""

      - name: product_pack_size
        data_type: string
        description: ""

  - name: obt_helium_10_keyword_rankings
    description: ""
    columns:
      - name: asin
        data_type: string
        description: ""

      - name: title
        data_type: string
        description: ""

      - name: keyword
        data_type: string
        description: ""

      - name: created_at
        data_type: datetime
        description: ""

      - name: date_added
        data_type: timestamp
        description: ""

      - name: updated_at
        data_type: datetime
        description: ""

      - name: marketplace_url
        data_type: string
        description: ""

      - name: organic_rank
        data_type: int64
        description: ""

      - name: search_volume
        data_type: numeric
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: sponsored_position
        data_type: numeric
        description: ""

  - name: obt_sqp_brand
    description: ""
    columns:
      - name: week
        data_type: string
        description: ""

      - name: start_date
        data_type: date
        description: ""

      - name: end_date
        data_type: date
        description: ""

      - name: created_at
        data_type: datetime
        description: ""

      - name: updated_at
        data_type: datetime
        description: ""

      - name: reporting_date
        data_type: date
        description: ""

      - name: reporting_range
        data_type: string
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: search_query
        data_type: string
        description: ""

      - name: clicks_price
        data_type: numeric
        description: ""

      - name: cart_adds_price
        data_type: numeric
        description: ""

      - name: purchases_price
        data_type: numeric
        description: ""

      - name: clicks_click_rate
        data_type: numeric
        description: ""

      - name: clicks_brand_count
        data_type: int64
        description: ""

      - name: clicks_brand_price
        data_type: numeric
        description: ""

      - name: clicks_brand_share
        data_type: numeric
        description: ""

      - name: clicks_total_count
        data_type: int64
        description: ""

      - name: search_query_score
        data_type: int64
        description: ""

      - name: search_query_volume
        data_type: int64
        description: ""

      - name: cart_adds_brand_count
        data_type: int64
        description: ""

      - name: cart_adds_brand_price
        data_type: numeric
        description: ""

      - name: cart_adds_brand_share
        data_type: numeric
        description: ""

      - name: cart_adds_total_count
        data_type: int64
        description: ""

      - name: purchases_brand_count
        data_type: int64
        description: ""

      - name: purchases_brand_price
        data_type: numeric
        description: ""

      - name: purchases_brand_share
        data_type: numeric
        description: ""

      - name: purchases_total_count
        data_type: int64
        description: ""

      - name: cart_adds_cart_add_rate
        data_type: numeric
        description: ""

      - name: impressions_brand_count
        data_type: int64
        description: ""

      - name: impressions_brand_share
        data_type: numeric
        description: ""

      - name: impressions_total_count
        data_type: int64
        description: ""

      - name: purchases_purchase_rate
        data_type: numeric
        description: ""

      - name: clicks_1d_shipping_speed
        data_type: int64
        description: ""

      - name: clicks_2d_shipping_speed
        data_type: int64
        description: ""

      - name: cart_adds_1d_shipping_speed
        data_type: int64
        description: ""

      - name: cart_adds_2d_shipping_speed
        data_type: int64
        description: ""

      - name: purchases_1d_shipping_speed
        data_type: int64
        description: ""

      - name: purchases_2d_shipping_speed
        data_type: int64
        description: ""

      - name: clicks_same_day_shipping_speed
        data_type: int64
        description: ""

      - name: cart_adds_same_day_shipping_speed
        data_type: int64
        description: ""

      - name: purchases_same_day_shipping_speed
        data_type: int64
        description: ""

  - name: obt_sqp_weekly_asin
    description: ""
    columns:
      - name: asin
        data_type: string
        description: ""

      - name: start_date
        data_type: date
        description: ""

      - name: end_date
        data_type: date
        description: ""

      - name: created_at
        data_type: datetime
        description: ""

      - name: updated_at
        data_type: datetime
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: search_query
        data_type: string
        description: ""

      - name: search_query_score
        data_type: numeric
        description: ""

      - name: search_query_volume
        data_type: numeric
        description: ""

      - name: asin_click_count
        data_type: numeric
        description: ""

      - name: asin_click_share
        data_type: numeric
        description: ""

      - name: asin_cart_add_count
        data_type: numeric
        description: ""

      - name: asin_cart_add_share
        data_type: numeric
        description: ""

      - name: asin_purchase_count
        data_type: numeric
        description: ""

      - name: asin_purchase_share
        data_type: numeric
        description: ""

      - name: asin_impression_count
        data_type: numeric
        description: ""

      - name: asin_impression_share
        data_type: numeric
        description: ""

      - name: asin_median_click_price
        data_type: numeric
        description: ""

      - name: asin_median_click_price_amount_usd
        data_type: numeric
        description: ""

      - name: asin_median_cart_add_price
        data_type: numeric
        description: ""

      - name: asin_median_cart_add_price_amount_usd
        data_type: numeric
        description: ""

      - name: asin_median_purchase_price
        data_type: numeric
        description: ""

      - name: asin_median_purchase_price_amount_usd
        data_type: numeric
        description: ""

      - name: total_click_count
        data_type: numeric
        description: ""

      - name: total_click_rate
        data_type: numeric
        description: ""

      - name: total_cart_add_count
        data_type: numeric
        description: ""

      - name: total_cart_add_rate
        data_type: numeric
        description: ""

      - name: total_purchase_count
        data_type: numeric
        description: ""

      - name: total_purchase_rate
        data_type: numeric
        description: ""

      - name: total_median_cart_add_price
        data_type: numeric
        description: ""

      - name: total_median_cart_add_price_amount_usd
        data_type: numeric
        description: ""

      - name: total_median_purchase_price
        data_type: numeric
        description: ""

      - name: total_median_purchase_price_amount_usd
        data_type: numeric
        description: ""

      - name: total_median_click_price_amount_usd
        data_type: numeric
        description: ""

      - name: total_query_impression_count
        data_type: numeric
        description: ""

      - name: total_one_day_shipping_click_count
        data_type: numeric
        description: ""

      - name: total_one_day_shipping_cart_add_count
        data_type: numeric
        description: ""

      - name: total_one_day_shipping_purchase_count
        data_type: numeric
        description: ""

      - name: total_two_day_shipping_click_count
        data_type: numeric
        description: ""

      - name: total_two_day_shipping_cart_add_count
        data_type: numeric
        description: ""

      - name: total_two_day_shipping_purchase_count
        data_type: numeric
        description: ""

      - name: total_same_day_shipping_click_count
        data_type: numeric
        description: ""

      - name: total_same_day_shipping_cart_add_count
        data_type: numeric
        description: ""

      - name: total_same_day_shipping_purchase_count
        data_type: numeric
        description: ""