version: 2

models:
  - name: obt_orders_per_asin_and_date
    description: ""
    columns:
      - name: purchase_date
        data_type: date
        description: ""
      - name: marketplace
        data_type: string
        description: ""
      - name: order_status
        data_type: string
        description: ""
      - name: asin
        data_type: string
        description: ""
      - name: seller_sku
        data_type: string
        description: ""
      - name: product_code
        data_type: string
        description: ""
      - name: quantity_ordered
        data_type: int64
        description: ""
      - name: net_item_price_per_unit
        data_type: numeric
        description: ""
      - name: item_price_amount
        data_type: numeric
        description: ""
      - name: promotion_discount_amount
        data_type: numeric
        description: ""
      - name: item_tax_amount
        data_type: numeric
        description: ""
      - name: output_vat
        data_type: numeric
        description: ""
      - name: net_item_price_amount
        data_type: numeric
        description: ""
      - name: referral_fees
        data_type: numeric
        description: ""
      - name: coupon_fee
        data_type: numeric
        description: ""
      - name: item_price_currency_code
        data_type: string
        description: ""
      - name: is_vine
        data_type: boolean
        description: ""
      - name: is_replacement_order
        data_type: boolean
        description: ""
      - name: tenant_id
        data_type: int64
        description: ""