version: 2

models:
  - name: fct_aggregated_orders
    description: ""
    columns:
      - name: purchase_date
        data_type: date
        description: ""

      - name: product_sk
        data_type: string
        description: ""

      - name: marketplace_sk
        data_type: string
        description: ""

      - name: tenant_sk
        data_type: string
        description: ""

      - name: order_status
        data_type: string
        description: ""

      - name: is_vine
        data_type: boolean
        description: ""

      - name: is_replacement_order
        data_type: boolean
        description: ""

      - name: quantity_ordered
        data_type: int64
        description: ""

      - name: item_price_amount_usd
        data_type: numeric
        description: ""

      - name: coupon_fee_usd
        data_type: numeric
        description: ""

      - name: item_tax_amount_usd
        data_type: numeric
        description: ""

      - name: uk_output_vat_usd
        data_type: numeric
        description: ""

      - name: promotion_discount_amount_usd
        data_type: numeric
        description: ""

      - name: net_item_price_per_unit_usd
        data_type: numeric
        description: ""

      - name: net_item_price_amount_usd
        data_type: numeric
        description: ""

      - name: cogs_usd
        data_type: numeric
        description: ""

      - name: est_storage_fee_usd
        data_type: numeric
        description: ""

      - name: est_returns_cost_usd
        data_type: numeric
        description: ""

      - name: amazon_fees_usd
        data_type: float64
        description: ""