version: 2

sources:
  - name: product_pricing
    tables:
      - name: competitive_pricing
        columns:
          - name: _airbyte_raw_id
            data_type: string
          - name: _airbyte_extracted_at
            data_type: timestamp
          - name: _airbyte_meta
            data_type: json
          - name: _airbyte_generation_id
            data_type: int64
          - name: asin
            data_type: string
          - name: date
            data_type: date
          - name: status
            data_type: string
          - name: tenant_id
            data_type: int64
          - name: created_at
            data_type: datetime
          - name: updated_at
            data_type: datetime
          - name: marketplace
            data_type: string
          - name: customer_type
            data_type: string
          - name: product_sales_rankings
            data_type: string
          - name: product_identifiers_marketplace_asin_asin
            data_type: string
          - name: product_competitive_pricing_competitive_prices
            data_type: string
          - name: product_identifiers_marketplace_asin_marketplace_id
            data_type: string
          - name: product_competitive_pricing_number_of_offer_listings
            data_type: string