version: 2

models:
  - name: int_convert_sp_advertised_product_amounts_to_usd
    description: ""
    columns:
      - name: campaign_date
        data_type: date
        description: ""

      - name: created_at
        data_type: datetime
        description: ""

      - name: updated_at
        data_type: datetime
        description: ""

      - name: ad_id
        data_type: string
        description: ""

      - name: ad_group_id
        data_type: string
        description: ""

      - name: campaign_id
        data_type: string
        description: ""

      - name: portfolio_id
        data_type: string
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: ad_group_name
        data_type: string
        description: ""

      - name: campaign_name
        data_type: string
        description: ""

      - name: campaign_status
        data_type: string
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: advertised_sku
        data_type: string
        description: ""

      - name: advertised_asin
        data_type: string
        description: ""

      - name: campaign_budget_type
        data_type: string
        description: ""

      - name: impressions
        data_type: int64
        description: ""

      - name: clicks
        data_type: int64
        description: ""

      - name: purchases_14d
        data_type: int64
        description: ""

      - name: purchases_same_sku_14d
        data_type: int64
        description: ""

      - name: acos_clicks_14d
        data_type: numeric
        description: ""

      - name: roas_clicks_14d
        data_type: numeric
        description: ""

      - name: click_through_rate
        data_type: numeric
        description: ""

      - name: units_sold_clicks_14d
        data_type: int64
        description: ""

      - name: units_sold_same_sku_14d
        data_type: int64
        description: ""

      - name: kindle_edition_normalized_pages_read_14d
        data_type: int64
        description: ""

      - name: kindle_edition_normalized_pages_royalties_14d
        data_type: int64
        description: ""

      - name: cost_usd
        data_type: numeric
        description: ""

      - name: spend_usd
        data_type: numeric
        description: ""

      - name: sales_14d_usd
        data_type: numeric
        description: ""

      - name: cost_per_click_usd
        data_type: numeric
        description: ""

      - name: campaign_budget_amount_usd
        data_type: numeric
        description: ""

      - name: attributed_sales_same_sku_14d_usd
        data_type: numeric
        description: ""

  - name: int_kpi_tracker__union_all_sp_campaigns
    description: ""
    columns:
      - name: campaign_date
        data_type: date
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: portfolio_code
        data_type: string
        description: ""

      - name: total_impressions
        data_type: int64
        description: ""

      - name: total_clicks
        data_type: int64
        description: ""

      - name: total_cost_usd
        data_type: numeric
        description: ""

      - name: total_units_sold_clicks_7d
        data_type: int64
        description: ""

      - name: total_sales_7d_usd
        data_type: numeric
        description: ""