version: 2

models:
  - name: stg_orders__amazon_order_items
    description: "Handles nulls in some columns"
    columns:
      - name: asin
        data_type: string
        description: ""
      - name: tenant_id
        data_type: int64
        description: ""
      - name: order_item_id
        data_type: int64
        description: ""
      - name: promotion_ids
        data_type: string
        description: ""
      - name: amazon_order_id
        data_type: string
        description: ""
      - name: title
        data_type: string
        description: ""
      - name: seller_sku
        data_type: string
        description: ""
      - name: marketplace
        data_type: string
        description: ""
      - name: tax_collection_model
        data_type: string
        description: ""
      - name: item_tax_currency_code
        data_type: string
        description: ""
      - name: item_price_currency_code
        data_type: string
        description: ""
      - name: shipping_tax_currency_code
        data_type: string
        description: ""
      - name: shipping_price_currency_code
        data_type: string
        description: ""
      - name: shipping_discount_currency_code
        data_type: string
        description: ""
      - name: promotion_discount_currency_code
        data_type: string
        description: ""
      - name: tax_collection_responsible_party
        data_type: string
        description: ""
      - name: shipping_discount_tax_currency_code
        data_type: string
        description: ""
      - name: promotion_discount_tax_currency_code
        data_type: string
        description: ""
      - name: buyer_info_gift_wrap_tax_currency_code
        data_type: string
        description: ""
      - name: buyer_info_gift_wrap_price_currency_code
        data_type: string
        description: ""
      - name: quantity_ordered
        data_type: int64
        description: ""
      - name: quantity_shipped
        data_type: int64
        description: ""
      - name: shipping_tax_amount
        data_type: numeric
        description: ""
      - name: shipping_price_amount
        data_type: numeric
        description: ""
      - name: shipping_discount_amount
        data_type: numeric
        description: ""
      - name: product_info_number_of_items
        data_type: int64
        description: ""
      - name: shipping_discount_tax_amount
        data_type: numeric
        description: ""
      - name: buyer_info_gift_wrap_tax_amount
        data_type: numeric
        description: ""
      - name: buyer_info_gift_wrap_price_amount
        data_type: numeric
        description: ""
      - name: is_gift
        data_type: string
        description: ""
      - name: is_transparency
        data_type: boolean
        description: ""
      - name: created_at
        data_type: datetime
        description: ""
      - name: updated_at
        data_type: datetime
        description: ""
      - name: item_tax_amount
        data_type: numeric
        description: ""
      - name: item_price_amount
        data_type: numeric
        description: ""
      - name: promotion_discount_amount
        data_type: numeric
        description: ""
      - name: promotion_discount_tax_amount
        data_type: numeric
        description: ""