version: 2

sources:
  - name: orders
    tables:
      - name: amazon_order_items
        columns:
          - name: _airbyte_raw_id
            data_type: string
          - name: _airbyte_extracted_at
            data_type: timestamp
          - name: _airbyte_meta
            data_type: json
          - name: _airbyte_generation_id
            data_type: int64
          - name: asin
            data_type: string
          - name: title
            data_type: string
          - name: is_gift
            data_type: string
          - name: tenant_id
            data_type: int64
          - name: created_at
            data_type: datetime
          - name: seller_sku
            data_type: string
          - name: updated_at
            data_type: datetime
          - name: marketplace
            data_type: string
          - name: order_item_id
            data_type: int64
          - name: promotion_ids
            data_type: string
          - name: amazon_order_id
            data_type: string
          - name: is_transparency
            data_type: boolean
          - name: item_tax_amount
            data_type: numeric
          - name: quantity_ordered
            data_type: int64
          - name: quantity_shipped
            data_type: int64
          - name: item_price_amount
            data_type: numeric
          - name: shipping_tax_amount
            data_type: numeric
          - name: tax_collection_model
            data_type: string
          - name: shipping_price_amount
            data_type: numeric
          - name: item_tax_currency_code
            data_type: string
          - name: item_price_currency_code
            data_type: string
          - name: shipping_discount_amount
            data_type: numeric
          - name: promotion_discount_amount
            data_type: numeric
          - name: shipping_tax_currency_code
            data_type: string
          - name: product_info_number_of_items
            data_type: int64
          - name: shipping_discount_tax_amount
            data_type: numeric
          - name: shipping_price_currency_code
            data_type: string
          - name: promotion_discount_tax_amount
            data_type: numeric
          - name: buyer_info_gift_wrap_tax_amount
            data_type: numeric
          - name: shipping_discount_currency_code
            data_type: string
          - name: promotion_discount_currency_code
            data_type: string
          - name: tax_collection_responsible_party
            data_type: string
          - name: buyer_info_gift_wrap_price_amount
            data_type: numeric
          - name: shipping_discount_tax_currency_code
            data_type: string
          - name: promotion_discount_tax_currency_code
            data_type: string
          - name: buyer_info_gift_wrap_tax_currency_code
            data_type: string
          - name: buyer_info_gift_wrap_price_currency_code
            data_type: string

      - name: amazon_order_items_detailed_view
        columns:
          - name: amazon_order_id
            data_type: string
          - name: order_item_id
            data_type: int64
          - name: purchase_datetime
            data_type: timestamp
          - name: purchase_date
            data_type: date
          - name: marketplace
            data_type: string
          - name: sales_channel
            data_type: string
          - name: asin
            data_type: string
          - name: seller_sku
            data_type: string
          - name: order_status
            data_type: string
          - name: quantity_ordered
            data_type: int64
          - name: promotion_ids
            data_type: string
          - name: product_info_number_of_items
            data_type: int64
          - name: item_price_currency_code
            data_type: string
          - name: item_price_amount
            data_type: numeric
          - name: item_tax_amount
            data_type: numeric
          - name: promotion_discount_tax_currency_code
            data_type: string
          - name: output_vat
            data_type: numeric
          - name: item_tax_currency_code
            data_type: string
          - name: promotion_discount_tax_amount
            data_type: numeric
          - name: promotion_discount_currency_code
            data_type: string
          - name: promotion_discount_amount
            data_type: numeric
          - name: coupon_fee
            data_type: numeric
          - name: tax_collection_model
            data_type: string
          - name: tax_collection_responsible_party
            data_type: string
          - name: is_prime
            data_type: boolean
          - name: is_replacement_order
            data_type: boolean
          - name: replaced_order_id
            data_type: string
          - name: is_gift
            data_type: string
          - name: is_vine
            data_type: boolean
          - name: tenant_id
            data_type: int64

      - name: amazon_orders
        columns:
          - name: _airbyte_raw_id
            data_type: string
          - name: _airbyte_extracted_at
            data_type: timestamp
          - name: _airbyte_meta
            data_type: json
          - name: _airbyte_generation_id
            data_type: int64
          - name: is_ispu
            data_type: boolean
          - name: is_prime
            data_type: boolean
          - name: tenant_id
            data_type: int64
          - name: created_at
            data_type: datetime
          - name: order_type
            data_type: string
          - name: updated_at
            data_type: datetime
          - name: marketplace
            data_type: string
          - name: order_status
            data_type: string
          - name: is_sold_by_ab
            data_type: boolean
          - name: purchase_date
            data_type: timestamp
          - name: sales_channel
            data_type: string
          - name: marketplace_id
            data_type: string
          - name: payment_method
            data_type: string
          - name: amazon_order_id
            data_type: string
          - name: seller_order_id
            data_type: string
          - name: is_premium_order
            data_type: boolean
          - name: last_update_date
            data_type: timestamp
          - name: latest_ship_date
            data_type: timestamp
          - name: is_business_order
            data_type: boolean
          - name: replaced_order_id
            data_type: string
          - name: earliest_ship_date
            data_type: timestamp
          - name: order_total_amount
            data_type: numeric
          - name: ship_service_level
            data_type: string
          - name: fulfillment_channel
            data_type: string
          - name: has_regulated_items
            data_type: boolean
          - name: is_replacement_order
            data_type: boolean
          - name: is_access_point_order
            data_type: boolean
          - name: shipping_address_city
            data_type: string
          - name: buyer_info_buyer_email
            data_type: string
          - name: payment_method_details
            data_type: string
          - name: number_of_items_shipped
            data_type: int64
          - name: is_global_express_enabled
            data_type: boolean
          - name: number_of_items_unshipped
            data_type: int64
          - name: order_total_currency_code
            data_type: string
          - name: shipping_address_postal_code
            data_type: string
          - name: shipping_address_country_code
            data_type: string
          - name: shipment_service_level_category
            data_type: string
          - name: shipping_address_state_or_region
            data_type: string

      - name: amazon_orders_summary_view
        columns:
          - name: purchase_date
            data_type: date
          - name: marketplace
            data_type: string
          - name: order_status
            data_type: string
          - name: asin
            data_type: string
          - name: seller_sku
            data_type: string
          - name: product_code
            data_type: string
          - name: quantity_ordered
            data_type: int64
          - name: net_item_price_per_unit
            data_type: numeric
          - name: item_price_amount
            data_type: numeric
          - name: promotion_discount_amount
            data_type: numeric
          - name: item_tax_amount
            data_type: numeric
          - name: output_vat
            data_type: numeric
          - name: net_item_price_amount
            data_type: numeric
          - name: referral_fees
            data_type: numeric
          - name: coupon_fee
            data_type: numeric
          - name: item_price_currency_code
            data_type: string
          - name: is_vine
            data_type: boolean
          - name: is_replacement_order
            data_type: boolean
          - name: tenant_id
            data_type: int64