version: 2

models:
  - name: int_dedup_financial_events_item_fees
    description: ""
    columns:
      - name: amazon_order_id
        data_type: string
        description: ""

      - name: order_item_id
        data_type: string
        description: ""

      - name: posted_date
        data_type: string
        description: ""

      - name: seller_sku
        data_type: string
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: created_at
        data_type: string
        description: ""

      - name: quantity_shipped
        data_type: int64
        description: ""

      - name: item_fee__fee_type
        data_type: string
        description: ""

      - name: item_fee__currency_code
        data_type: string
        description: ""

      - name: item_fee__fee_amount
        data_type: float64
        description: ""

  - name: int_aggregate_financial_events_item_fees
    description: ""
    columns:
      - name: amazon_order_id
        data_type: string
        description: ""

      - name: order_item_id
        data_type: string
        description: ""

      - name: seller_sku
        data_type: string
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: item_fee__fee_amount_usd
        data_type: float64
        description: ""