version: 2

models:
  - name: int_calculate_fields_for_bb_listings_items
    description: ""
    columns:
      - name: sku
        data_type: string
        description: ""

      - name: asin
        data_type: string
        description: ""

      - name: product_type
        data_type: string
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: parent_code
        data_type: string
        description: ""

      - name: shaker_code
        data_type: string
        description: ""

      - name: portfolio_code
        data_type: string
        description: ""

      - name: product_code
        data_type: string
        description: ""

  - name: int_calculate_fields_for_rymora_listings_items
    description: ""
    columns:
      - name: sku
        data_type: string
        description: ""

      - name: asin
        data_type: string
        description: ""

      - name: product_type
        data_type: string
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: parent_code
        data_type: string
        description: ""

      - name: shaker_code
        data_type: string
        description: ""

      - name: portfolio_code
        data_type: string
        description: ""

      - name: product_code
        data_type: string
        description: ""