dbt_project:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: dbt_prod
      threads: 4
      keyfile: $HOME/gcp-key.json
      location: US