dbt_project:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: dbt_prod
      threads: 4
      keyfile: "/home/runner/gcp-key.json"
      location: US