version: 2

models:
  - name: int_kpi_tracker__aggregate_sp_campaigns
    description: ""
    columns:
      - name: campaign_date
        data_type: date
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: portfolio_code
        data_type: string
        description: ""

      - name: total_impressions
        data_type: int64
        description: ""

      - name: total_clicks
        data_type: int64
        description: ""

      - name: total_units_sold_clicks_1d
        data_type: int64
        description: ""

      - name: total_units_sold_clicks_7d
        data_type: int64
        description: ""

      - name: total_units_sold_clicks_14d
        data_type: int64
        description: ""

      - name: total_units_sold_clicks_30d
        data_type: int64
        description: ""

      - name: total_purchases_1d
        data_type: int64
        description: ""

      - name: total_purchases_7d
        data_type: int64
        description: ""

      - name: total_purchases_14d
        data_type: int64
        description: ""

      - name: total_purchases_30d
        data_type: int64
        description: ""

      - name: total_click_through_rate
        data_type: numeric
        description: ""

      - name: total_top_of_search_impression_share
        data_type: numeric
        description: ""

      - name: total_campaign_budget_amount_usd
        data_type: numeric
        description: ""

      - name: total_cost_usd
        data_type: numeric
        description: ""

      - name: total_sales_1d_usd
        data_type: numeric
        description: ""

      - name: total_sales_7d_usd
        data_type: numeric
        description: ""

      - name: total_sales_14d_usd
        data_type: numeric
        description: ""

      - name: total_sales_30d_usd
        data_type: numeric
        description: ""

      - name: total_cost_per_click_usd
        data_type: numeric
        description: ""

  - name: int_kpi_tracker__aggregate_sp_cc
    description: ""
    columns:
      - name: campaign_date
        data_type: date
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: portfolio_code
        data_type: string
        description: ""

      - name: total_impressions
        data_type: int64
        description: ""

      - name: total_clicks
        data_type: int64
        description: ""

      - name: _7_day_total_orders
        data_type: int64
        description: ""

      - name: total_click_thru_rate
        data_type: numeric
        description: ""

      - name: total_last_year_impressions
        data_type: numeric
        description: ""

      - name: total_last_year_clicks
        data_type: numeric
        description: ""

      - name: total_advertising_cost_of_sales
        data_type: numeric
        description: ""

      - name: total_return_on_advertising_spend
        data_type: numeric
        description: ""

      - name: total_spend_usd
        data_type: numeric
        description: ""

      - name: total_budget_usd
        data_type: numeric
        description: ""

      - name: _7_day_total_sales_usd
        data_type: numeric
        description: ""

      - name: total_cost_per_click_usd
        data_type: numeric
        description: ""

      - name: total_last_year_spend_usd
        data_type: numeric
        description: ""

      - name: total_last_year_cost_per_click_usd
        data_type: numeric
        description: ""