version: 2

sources:
  - name: public
    tables:
      - name: amazon_advertising_portfolios
        columns:
          - name: _airbyte_raw_id
            data_type: string
          - name: _airbyte_extracted_at
            data_type: timestamp
          - name: _airbyte_meta
            data_type: json
          - name: _airbyte_generation_id
            data_type: int64
          - name: name
            data_type: string
          - name: state
            data_type: string
          - name: in_budget
            data_type: boolean
          - name: tenant_id
            data_type: int64
          - name: created_at
            data_type: datetime
          - name: updated_at
            data_type: datetime
          - name: marketplace
            data_type: string
          - name: portfolio_id
            data_type: int64
          - name: creation_date
            data_type: datetime
          - name: serving_status
            data_type: string
          - name: last_updated_date
            data_type: datetime