version: 2

models:
  - name: int_combine_cogs_ww
    description: ""
    columns:
      - name: start_date
        data_type: date
        description: ""

      - name: end_date
        data_type: date
        description: ""

      - name: parent_product
        data_type: string
        description: ""

      - name: product_code
        data_type: string
        description: ""

      - name: sku
        data_type: string
        description: ""

      - name: asin
        data_type: string
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: currency_code
        data_type: string
        description: ""

      - name: cogs
        data_type: numeric
        description: ""

      - name: fba_fee
        data_type: numeric
        description: ""

      - name: storage_fee
        data_type: numeric
        description: ""

      - name: returns_cost
        data_type: numeric
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""