version: 2

models:
  - name: int_kpi_tracker__union_all_sb_campaigns
    description: ""
    columns:
      - name: campaign_date
        data_type: date
        description: ""

      - name: portfolio_code
        data_type: string
        description: ""

      - name: marketplace
        data_type: string
        description: ""

      - name: tenant_id
        data_type: int64
        description: ""

      - name: total_impressions
        data_type: int64
        description: ""

      - name: total_clicks
        data_type: int64
        description: ""

      - name: total_cost_usd
        data_type: numeric
        description: ""

      - name: total_units_sold_clicks
        data_type: int64
        description: ""

      - name: total_purchases_clicks
        data_type: int64
        description: ""

      - name: total_sales_clicks_usd
        data_type: numeric
        description: ""